# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cocktail DB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cocktail DB
  pod 'Moya', '~> 13.0.0' 
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SDWebImage', '~> 5.0'
end
